service: sls-with-layer

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  timeout: 300

functions:
  chromium-test:
    handler: index.handler
    layers:
      - !Ref ChromiumtestLambdaLayer

layers:
  chromiumtest:
    package:
      artifact: ../../chromium.zip
